// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

NumericVector depth2dcpp(SEXP R_x, SEXP R_y);

static bool validateExported(const std::string& sig) {
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("NumericVector(*depth2dcpp)(SEXP,SEXP)");
    }
    return signatures.find(sig) != signatures.end();
}

RCPP_MODULE(depthproc_RcppExports) {
    Rcpp::function("depth2dcpp", &depth2dcpp, Rcpp::List::create(Rcpp::Named("R_x"), Rcpp::Named("R_y")));
    Rcpp::function("RcppExports_validateExported", &validateExported);
}
